from model import Card, Suit

B1 = Card(Suit.Blue, 1)
B2 = Card(Suit.Blue, 2)
B3 = Card(Suit.Blue, 3)
B4 = Card(Suit.Blue, 4)
B5 = Card(Suit.Blue, 5)
B6 = Card(Suit.Blue, 6)
B7 = Card(Suit.Blue, 7)
B8 = Card(Suit.Blue, 8)
B9 = Card(Suit.Blue, 9)

Y1 = Card(Suit.Yellow, 1)
Y2 = Card(Suit.Yellow, 2)
Y3 = Card(Suit.Yellow, 3)
Y4 = Card(Suit.Yellow, 4)
Y5 = Card(Suit.Yellow, 5)
Y6 = Card(Suit.Yellow, 6)
Y7 = Card(Suit.Yellow, 7)
Y8 = Card(Suit.Yellow, 8)
Y9 = Card(Suit.Yellow, 9)

M1 = Card(Suit.Magenta, 1)
M2 = Card(Suit.Magenta, 2)
M3 = Card(Suit.Magenta, 3)
M4 = Card(Suit.Magenta, 4)
M5 = Card(Suit.Magenta, 5)
M6 = Card(Suit.Magenta, 6)
M7 = Card(Suit.Magenta, 7)
M8 = Card(Suit.Magenta, 8)
M9 = Card(Suit.Magenta, 9)

G1 = Card(Suit.Green, 1)
G2 = Card(Suit.Green, 2)
G3 = Card(Suit.Green, 3)
G4 = Card(Suit.Green, 4)
G5 = Card(Suit.Green, 5)
G6 = Card(Suit.Green, 6)
G7 = Card(Suit.Green, 7)
G8 = Card(Suit.Green, 8)
G9 = Card(Suit.Green, 9)

R1 = Card(Suit.Rocket, 1)
R2 = Card(Suit.Rocket, 2)
R3 = Card(Suit.Rocket, 3)
R4 = Card(Suit.Rocket, 4)
